#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_dash/version.py`)
PAC_ELECTRUM_VERSION=${VERSION_STRING[2]}
PAC_ELECTRUM_VERSION=${PAC_ELECTRUM_VERSION#\'}
PAC_ELECTRUM_VERSION=${PAC_ELECTRUM_VERSION%\'}
export PAC_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_dash/version.py`)
PAC_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
PAC_ELECTRUM_APK_VERSION=${PAC_ELECTRUM_APK_VERSION#\'}
PAC_ELECTRUM_APK_VERSION=${PAC_ELECTRUM_APK_VERSION%\'}
export PAC_ELECTRUM_APK_VERSION
